import Head from 'next/head'

import styles from '../styles/Main.module.css'
import React from 'react';
import { post } from '../utils/request';
import Summoner from '../components/index/Summoner';
import Champions from '../components/index/Champions';
import Regions from '../components/index/Regions';
export default function Home() {
  const [activeRegions, setActiveRegions] = React.useState("NA1");
  const [result, setResult] = React.useState([]);
  const [search,setSearch] = React.useState("");
  const searchingDetailRef = React.useRef();
  const searchInputRef = React.useRef();


  const getChamps = async (value) => {
    setSearch(value);
    if (value.length > 1) {
      searchingDetailRef.current.classList.add(styles.displayUnset);
      searchInputRef.current.classList.add(styles.removeRound);
      const response = await post("api/champions", { search: value }, { method: "post" });
      setResult(response.result);
    }
    else {
      searchingDetailRef.current.classList.remove(styles.displayUnset);
      searchInputRef.current.classList.remove(styles.removeRound);
      setResult([]);
    }


  }
  return (
    <div className={styles.container}>
      <Head>
        <title>LOGGER</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main} >
        <div className={styles.searchArea}>
          <h1 className='text-7xl text-slate-50'>LOGGER</h1>
          <div className={styles.searchInput} ref={searchInputRef}>
            <Regions activeRegions={activeRegions} setActiveRegions={setActiveRegions}></Regions>
            <input type="text" className='w-full' onChange={(e) => { getChamps(e.target.value); }} placeholder='Search for Champions , Summoners'></input>
            <div className={styles.searchingDetail} ref={searchingDetailRef}>
              <div className={styles.resultArea}>
                <Champions result={result}></Champions>
                <Summoner search={search} activeRegions={activeRegions}></Summoner>
              </div>
            </div>

          </div>
        </div>
        <video loop muted autoPlay>
          <source src="/assets/main.mp4" type="video/mp4" />
        </video>

      </main >


    </div >
  )
}
